import { test } from 'node:test';
import assert from 'node:assert/strict';
import { FakeAudioContext, SRC } from './fakes.mjs';

test('loadSample rejects on an HTTP error instead of reporting a decode failure', async () => {
    const { GranularEngine } = await import(SRC + 'audio/GranularEngine.js');
    const ctx = new FakeAudioContext();
    ctx.decodeAudioData = async () => { throw new Error('decode'); };
    const saved = globalThis.fetch;
    globalThis.fetch = async () => ({ ok: false, status: 404, statusText: 'Not Found', arrayBuffer: async () => new ArrayBuffer(0) });
    try {
        const e = new GranularEngine(ctx, ctx.createGain());
        await assert.rejects(() => e.loadSample('samples/missing.mp3'), /404/);
    } finally { globalThis.fetch = saved; }
});

test('getEventsInRange is not O(n) from index 0 on every call', async () => {
    const { AutomationLane } = await import(SRC + 'automation/AutomationLane.js');
    const lane = new AutomationLane();
    for (let i = 0; i < 20000; i++) lane.addEvent({ time: i * 0.001, voiceIndex: 0, type: 'move', params: {} });
    let scanned = 0;
    const orig = lane.events;
    // Proxy counts element reads.
    lane.events = new Proxy(orig, { get(t, k) { if (typeof k === 'string' && /^\d+$/.test(k)) scanned++; return t[k]; } });
    for (let t = 0; t < 20; t += 0.001) lane.getEventsInRange(t, t + 0.001);
    lane.events = orig;
    assert.ok(scanned < 500000, `rescanned ${scanned} elements — expected a cursor, not a full sweep per call`);
});

test('the ADSR curve is generated by exactly one function', async () => {
    const mod = await import(SRC + 'audio/envelopes.js');
    const src = await (await import('node:fs/promises')).readFile(
        new URL('../src/audio/envelopes.js', import.meta.url), 'utf8');
    const bodies = src.match(/const aEnd\s+= Math\.floor/g) || [];
    assert.equal(bodies.length, 1, 'two byte-identical ADSR generators still present');
    assert.equal(typeof mod.computeADSREnvelope, 'function');
});

test('InstanceState defaults sampleMissing to false, and a legacy session lacking the field restores to that default', async () => {
    const { InstanceState } = await import(SRC + 'state/InstanceState.js');

    const fresh = new InstanceState();
    assert.strictEqual(fresh.sampleMissing, false);

    // Simulate a session saved before `sampleMissing` existed: the key is absent
    // from the parsed JSON entirely, not present-and-undefined.
    const legacyData = fresh.toJSON();
    delete legacyData.sampleMissing;
    assert.ok(!('sampleMissing' in legacyData));

    const restored = InstanceState.fromJSON(legacyData);
    assert.strictEqual(restored.sampleMissing, false);
});

test('InstanceState round-trips sampleMissing=true through toJSON/fromJSON', async () => {
    const { InstanceState } = await import(SRC + 'state/InstanceState.js');

    const state = new InstanceState();
    state.sampleMissing = true;

    // Through a real JSON boundary (stringify/parse), not just object copying —
    // this is what SessionPersistence actually does.
    const json = JSON.parse(JSON.stringify(state.toJSON()));
    const restored = InstanceState.fromJSON(json);

    assert.strictEqual(restored.sampleMissing, true);
});
